"""Scheme and service comparison page."""

from __future__ import annotations

import uuid

import streamlit as st
from dotenv import load_dotenv

from lib.db import get_all_services, get_database, get_mongo_client, seed_services
from lib.i18n import language_selector
from lib.utils import inject_custom_css, render_custom_sidebar, render_page_header

load_dotenv()

st.set_page_config(page_title="Compare | LokMitra AI", page_icon="CM", layout="wide")
inject_custom_css()

if "session_id" not in st.session_state:
    st.session_state["session_id"] = str(uuid.uuid4())

language_selector()
render_custom_sidebar()

client = get_mongo_client()
db = get_database(client)
seed_services(db)

render_page_header(
    "Compare Services",
    "Select two or three services or schemes and compare type, eligibility, documents, official links, and overlapping requirements.",
    "Decision support",
)

services = get_all_services(db)
service_names = [s.get("name", "Unknown") for s in services]
selected_names = st.multiselect("Select schemes/services to compare (2-3)", service_names, max_selections=3)

if len(selected_names) < 2:
    st.info("Select at least two records to generate a comparison.")
else:
    selected_services = [s for s in services if s.get("name") in selected_names]

    rows = []
    for svc in selected_services:
        rows.append(
            {
                "Name": svc.get("name", "N/A"),
                "Type": svc.get("category", "N/A").capitalize(),
                "Eligibility": svc.get("eligibility", "N/A"),
                "Documents": len(svc.get("required_documents", [])),
                "Official link": svc.get("how_to_apply_link", "N/A"),
            }
        )
    st.dataframe(rows, use_container_width=True, hide_index=True)

    cols = st.columns(len(selected_services))
    for col, svc in zip(cols, selected_services):
        with col:
            with st.container(border=True):
                st.markdown(f"### {svc.get('name', 'N/A')}")
                st.caption(svc.get("description", ""))
                st.markdown("**Documents**")
                for doc in svc.get("required_documents", []):
                    st.markdown(f"- {doc}")
                link = svc.get("how_to_apply_link", "")
                if link:
                    st.markdown(f"[Official link]({link})")

    all_docs_sets = [set(svc.get("required_documents", [])) for svc in selected_services]
    common_docs = all_docs_sets[0]
    for docs in all_docs_sets[1:]:
        common_docs = common_docs.intersection(docs)

    st.markdown("### Document overlap")
    if common_docs:
        with st.container(border=True):
            for doc in sorted(common_docs):
                st.markdown(f"- {doc}")
            st.info(f"Prepare these {len(common_docs)} common documents first.")
    else:
        st.info("No common documents between the selected records.")

    comp_text = "SCHEME/SERVICE COMPARISON\n"
    comp_text += "=" * 50 + "\n\n"
    for svc in selected_services:
        comp_text += f"{svc.get('name', 'N/A')}\n"
        comp_text += f"   Type: {svc.get('category', 'N/A').capitalize()}\n"
        comp_text += f"   Eligibility: {svc.get('eligibility', 'N/A')}\n"
        comp_text += f"   Documents: {', '.join(svc.get('required_documents', []))}\n"
        comp_text += f"   Apply: {svc.get('how_to_apply_link', 'N/A')}\n\n"
    comp_text += "\n--- Generated by LokMitra AI ---\n"

    st.download_button(
        label="Download comparison",
        data=comp_text,
        file_name="scheme_comparison.txt",
        mime="text/plain",
        use_container_width=True,
    )
