"""Document checklist generator page."""

from __future__ import annotations

import uuid

import streamlit as st
from dotenv import load_dotenv

from lib.db import get_all_services, get_database, get_mongo_client, seed_services
from lib.i18n import language_selector
from lib.utils import inject_custom_css, render_custom_sidebar, render_empty_state, render_page_header

load_dotenv()

st.set_page_config(page_title="Checklist | LokMitra AI", page_icon="CK", layout="wide")
inject_custom_css()

if "session_id" not in st.session_state:
    st.session_state["session_id"] = str(uuid.uuid4())

language_selector()
render_custom_sidebar()

client = get_mongo_client()
db = get_database(client)
seed_services(db)

render_page_header(
    "Document Checklist",
    "Select a service or scheme and turn requirements into a progress checklist that can be downloaded for offline preparation.",
    "Readiness workflow",
)

services = get_all_services(db)
service_names = [s.get("name", "Unknown") for s in services]

if not service_names:
    render_empty_state("No services available", "Seed data could not be loaded.")
    st.stop()

selected_service_name = st.selectbox("Select a government service or scheme", service_names, key="checklist_service")
selected_service = next((s for s in services if s.get("name") == selected_service_name), None)

if selected_service:
    docs = selected_service.get("required_documents", [])
    service_name = selected_service.get("name", "Unknown")

    st.markdown(f"### Checklist for {service_name}")
    with st.container(border=True):
        st.markdown(f"**About:** {selected_service.get('description', 'N/A')}")
        st.markdown(f"**Eligibility:** {selected_service.get('eligibility', 'N/A')}")
        link = selected_service.get("how_to_apply_link", "")
        if link:
            st.markdown(f"**Official link:** [{link}]({link})")

    checklist_key = f"checklist_{service_name}"
    if checklist_key not in st.session_state:
        st.session_state[checklist_key] = {doc: False for doc in docs}

    if docs:
        checked_count = 0
        for i, doc in enumerate(docs):
            is_checked = st.checkbox(
                doc,
                value=st.session_state[checklist_key].get(doc, False),
                key=f"doc_check_{service_name}_{i}",
            )
            st.session_state[checklist_key][doc] = is_checked
            checked_count += int(is_checked)

        progress = checked_count / len(docs)
        st.progress(progress)
        status_cols = st.columns(3)
        with status_cols[0]:
            st.metric("Ready", checked_count)
        with status_cols[1]:
            st.metric("Remaining", len(docs) - checked_count)
        with status_cols[2]:
            st.metric("Completion", f"{progress * 100:.0f}%")

        checklist_text = f"Document Checklist - {service_name}\n"
        checklist_text += "=" * 50 + "\n\n"
        checklist_text += f"Service: {service_name}\n"
        checklist_text += f"Eligibility: {selected_service.get('eligibility', 'N/A')}\n"
        checklist_text += f"Apply at: {selected_service.get('how_to_apply_link', 'N/A')}\n\n"
        checklist_text += "Required Documents:\n"
        for doc in docs:
            check = "[x]" if st.session_state[checklist_key].get(doc, False) else "[ ]"
            checklist_text += f"  {check} {doc}\n"
        checklist_text += f"\nProgress: {checked_count}/{len(docs)} documents ready\n"
        checklist_text += "\n--- Generated by LokMitra AI ---\n"

        st.download_button(
            label="Download checklist",
            data=checklist_text,
            file_name=f"checklist_{service_name.replace(' ', '_').lower()}.txt",
            mime="text/plain",
            use_container_width=True,
        )
    else:
        st.info("No specific document requirements listed for this service.")
