"""Emergency Helplines Directory page for LokMitra AI.

Provides a searchable directory of important emergency numbers
and government helplines across India.
"""

import uuid

import streamlit as st
from dotenv import load_dotenv

from lib.db import get_all_helplines, get_database, get_mongo_client, seed_helplines
from lib.i18n import get_label, language_selector
from lib.utils import inject_custom_css, render_custom_sidebar

load_dotenv()

st.set_page_config(
    page_title="Emergency Helplines — LokMitra AI",
    page_icon="🆘",
    layout="wide",
)

# --- Unified Custom CSS Injected ---
inject_custom_css()

if "session_id" not in st.session_state:
    st.session_state["session_id"] = str(uuid.uuid4())

lang = language_selector()

# --- Render Custom Sidebar Nav ---
render_custom_sidebar()

client = get_mongo_client()
db = get_database(client)
seed_helplines(db)

# --- Header ---
st.markdown(
    "<h1 style='color:#0F172A;'>🆘 Emergency Helplines</h1>",
    unsafe_allow_html=True,
)
st.markdown(
    "<p style='color:#64748B;'>"
    "Quick access to important emergency numbers and government helplines. "
    "Save these numbers — they could save a life.</p>",
    unsafe_allow_html=True,
)

# --- Emergency Banner ---
st.markdown(
    "<div style='background:linear-gradient(135deg, #DC2626, #EF4444); "
    "color:white; padding:1.5rem; border-radius:12px; text-align:center; "
    "margin:1rem 0;'>"
    "<h2 style='color:white; margin:0;'>🚨 In an Emergency, Call 112</h2>"
    "<p style='color:#FEE2E2; margin:0.5rem 0 0 0;'>"
    "India's unified emergency number — connects to Police, Fire & Ambulance</p>"
    "</div>",
    unsafe_allow_html=True,
)

st.markdown("---")

# --- Search & Filter ---
helplines = get_all_helplines(db)

col_search, col_filter = st.columns([3, 1])

with col_search:
    search_query = st.text_input(
        label="🔍 Search helplines",
        placeholder="Search by name, category, or description...",
        key="helpline_search",
    )

with col_filter:
    categories = sorted(set(h.get("category", "Other") for h in helplines))
    categories.insert(0, "All Categories")
    selected_category = st.selectbox(
        label="Filter by Category",
        options=categories,
        key="helpline_category",
    )

# --- Filter ---
filtered = helplines
if search_query:
    q = search_query.lower()
    filtered = [
        h for h in filtered
        if q in h.get("name", "").lower()
        or q in h.get("description", "").lower()
        or q in h.get("category", "").lower()
        or q in h.get("number", "").lower()
    ]
if selected_category != "All Categories":
    filtered = [h for h in filtered if h.get("category") == selected_category]

# --- Display ---
if filtered:
    # Group by category
    grouped: dict[str, list] = {}
    for h in filtered:
        cat = h.get("category", "Other")
        if cat not in grouped:
            grouped[cat] = []
        grouped[cat].append(h)

    for category, items in grouped.items():
        st.markdown(f"### {category}")
        cols = st.columns(2)
        for i, helpline in enumerate(items):
            with cols[i % 2]:
                with st.container(border=True):
                    st.markdown(
                        f"<div style='display:flex; align-items:center; gap:1rem;'>"
                        f"<span style='font-size:2.5rem;'>{helpline.get('icon', '📞')}</span>"
                        f"<div>"
                        f"<div style='font-size:1.1rem; font-weight:600; color:#0F172A;'>"
                        f"{helpline.get('name', 'Unknown')}</div>"
                        f"<div style='font-size:1.8rem; font-weight:700; color:#2563EB;'>"
                        f"📞 {helpline.get('number', 'N/A')}</div>"
                        f"<div style='font-size:0.85rem; color:#64748B;'>"
                        f"{helpline.get('description', '')}</div>"
                        f"<div style='font-size:0.8rem; color:#059669; margin-top:0.25rem;'>"
                        f"🕐 {helpline.get('available', '24/7')}</div>"
                        f"</div></div>",
                        unsafe_allow_html=True,
                    )
        st.markdown("")
else:
    st.info("No helplines found matching your search.")

# --- Download All ---
st.markdown("---")
all_text = "EMERGENCY HELPLINES — INDIA\n"
all_text += "=" * 40 + "\n\n"
for h in helplines:
    all_text += f"{h.get('icon', '')} {h.get('name', '')}: {h.get('number', '')}\n"
    all_text += f"   {h.get('description', '')}\n"
    all_text += f"   Available: {h.get('available', '24/7')}\n\n"
all_text += "\n--- Generated by LokMitra AI ---\n"

st.download_button(
    label="📥 Download All Helpline Numbers",
    data=all_text,
    file_name="emergency_helplines_india.txt",
    mime="text/plain",
    use_container_width=True,
)
