"""Emergency helplines directory page."""

from __future__ import annotations

import uuid

import streamlit as st
from dotenv import load_dotenv

from lib.db import get_all_helplines, get_database, get_mongo_client, seed_helplines
from lib.i18n import language_selector
from lib.utils import escape_html, inject_custom_css, render_custom_sidebar, render_empty_state, render_page_header

load_dotenv()

st.set_page_config(page_title="Helplines | LokMitra AI", page_icon="HL", layout="wide")
inject_custom_css()

if "session_id" not in st.session_state:
    st.session_state["session_id"] = str(uuid.uuid4())

language_selector()
render_custom_sidebar()

client = get_mongo_client()
db = get_database(client)
seed_helplines(db)

render_page_header(
    "Emergency Helplines",
    "Search and filter important emergency and public-service helplines. In immediate danger, call India's unified emergency number first.",
    "Citizen safety",
)

st.error("Emergency: call 112 for police, fire, or ambulance routing in India.")

helplines = get_all_helplines(db)
col_search, col_filter = st.columns([3, 1])
with col_search:
    search_query = st.text_input("Search helplines", placeholder="Search by name, category, description, or number...")
with col_filter:
    categories = sorted(set(h.get("category", "Other") for h in helplines))
    categories.insert(0, "All Categories")
    selected_category = st.selectbox("Filter by category", categories)

filtered = helplines
if search_query:
    q = search_query.lower()
    filtered = [
        h for h in filtered
        if q in h.get("name", "").lower()
        or q in h.get("description", "").lower()
        or q in h.get("category", "").lower()
        or q in h.get("number", "").lower()
    ]
if selected_category != "All Categories":
    filtered = [h for h in filtered if h.get("category") == selected_category]

if filtered:
    grouped: dict[str, list] = {}
    for h in filtered:
        grouped.setdefault(h.get("category", "Other"), []).append(h)

    for category, items in grouped.items():
        st.markdown(f"### {category}")
        cols = st.columns(2)
        for i, helpline in enumerate(items):
            with cols[i % 2]:
                with st.container(border=True):
                    st.markdown(f"#### {escape_html(helpline.get('name', 'Unknown'))}")
                    st.markdown(f"### {escape_html(helpline.get('number', 'N/A'))}")
                    st.caption(helpline.get("description", ""))
                    st.markdown(f"<span class='lm-pill'>{escape_html(helpline.get('available', '24/7'))}</span>", unsafe_allow_html=True)
else:
    render_empty_state("No helplines found", "Try another search term or category.")

all_text = "EMERGENCY HELPLINES - INDIA\n"
all_text += "=" * 40 + "\n\n"
for h in helplines:
    all_text += f"{h.get('name', '')}: {h.get('number', '')}\n"
    all_text += f"   {h.get('description', '')}\n"
    all_text += f"   Available: {h.get('available', '24/7')}\n\n"
all_text += "\n--- Generated by LokMitra AI ---\n"

st.download_button(
    label="Download all helpline numbers",
    data=all_text,
    file_name="emergency_helplines_india.txt",
    mime="text/plain",
    use_container_width=True,
)
